# Generated by Django 3.0.8 on 2020-07-18 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comments_for_user', models.CharField(blank=True, max_length=200)),
                ('comments_for_admin', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (0, 'Pending'), (-1, 'Rejected')])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(max_length=40)),
                ('group_name', models.CharField(blank=True, max_length=40)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('number_of_yale_nus_users', models.IntegerField()),
                ('number_of_external_users', models.IntegerField()),
                ('equipment_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Mixer', 'Mixer'), ('Drums', 'Drums'), ('Keyboard', 'Keyboard'), ('Microphones', 'Microphones'), ('Bass Amp', 'Bass Amp'), ('Acoustic Guitar Amp', 'Acoustic Guitar Amp'), ('Electric Guitar Amp', 'Electric Guitar Amp')], max_length=30), size=None)),
            ],
        ),
    ]
