# Generated by Django 3.0.8 on 2020-08-09 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200725_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='status',
        ),
        migrations.AddField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='acoustic_guitar_amp',
            field=models.BooleanField(default=False, verbose_name='Acoustic Guitar Amp'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bass_amp',
            field=models.BooleanField(default=False, verbose_name='Bass Amp'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drums',
            field=models.BooleanField(default=False, verbose_name='Drums'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='electric_guitar_amps',
            field=models.BooleanField(default=False, verbose_name='Electric Guitar Amps'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='group_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='keyboard',
            field=models.BooleanField(default=False, verbose_name='Keyboard'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='microphones',
            field=models.BooleanField(default=False, verbose_name='Microphones'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mixer',
            field=models.BooleanField(default=False, verbose_name='Mixer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_external_users',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(0)], verbose_name='No. of External Users'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_yale_nus_users',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='No. of Yale-NUS Users'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
